### ISSUE TITLE
Any chance that the comment.py has flaws?

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#12]
Hi, I downloaded the processed data provided in README, and it worked well with run.py. However, I want to process the raw data (e.g., data/Cantonese) myself using comment.py because I need to process my own data so that it can be reorganized in the format that run.py accepts. I ran the comment.py code and then this error occurred. 

```
Traceback (most recent call last):
  File "D:/zeroRumor_AAAI-main/data/Cantonese/comment.py", line 94, in <module>
    save_dict2npy(data_no_comment, './' + dataset + '/no_comment_baseline/', mode, train=train)
  File "D:/zeroRumor_AAAI-main/data/Cantonese/comment.py", line 27, in save_dict2npy
    a = np_table[randint(0, len(np_table))]
IndexError: list index out of range
```
the files are organized as:
![QQ截图20230815173700](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/791f119a-8673-4a56-8fff-354bca495fa6)

I ONLY changed these codes in comment.py (underlined with blue):
![QQ图片20230815173910](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/35312d6c-e0e2-409e-8efe-d9c0c37d988c)

Is it possible that the comment.py has flaws?

**Comment by zjk000** [comment]
It appears that comment.py does indeed have some glitches.
the files are organized as:
![organize](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/b3d69ac4-9d37-4a5a-bbd9-a9176ccf26de)
I changed these codes in comment.py:
![change1](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/6fa8783e-5e3b-4e14-816f-1199a50adfd5)
![change2](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/6d83a577-2871-4307-8792-eb6b1628aee2)
after running the comment.py that I edited, I get
![after](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/41cdba49-9e02-4706-9106-10fecf7725f6)
then I ran run.py, I assigned the parameter --data_dir the path to the directory shown in the screenshot above. Then I ran run.py
and got:
```
......
......
08/17/2023 17:00:40 - INFO - src.dataset -   Use demonstrations
08/17/2023 17:00:40 - INFO - src.dataset -   Label 0 to word ▁confirm (39563)
08/17/2023 17:00:40 - INFO - src.dataset -   Label 1 to word ▁rumor (107282)
08/17/2023 17:00:40 - INFO - src.dataset -   Creating/loading examples from dataset file at data/Cantonese/Cantonese
08/17/2023 17:00:40 - INFO - src.dataset -   Creating features from dataset file at data/Cantonese/Cantonese
08/17/2023 17:00:40 - INFO - src.dataset -   Saving features into cached file data/Cantonese/Cantonese\cached_test_XLMRobertaTokenizer_128_twi_False [took 0.011 s]
Traceback (most recent call last):
  File "D:/AAAI_ZeroRumor/zeroRumor_AAAI-main/run.py", line 707, in <module>
    main()
  File "D:/AAAI_ZeroRumor/zeroRumor_AAAI-main/run.py", line 515, in main
    FewShotDataset(data_args, tokenizer=tokenizer, mode="test", use_demo=("demo" in model_args.few_shot_type))
  File "D:\AAAI_ZeroRumor\zeroRumor_AAAI-main\src\dataset.py", line 481, in __init__
    self.features.append(self.convert_fn(
  File "D:\AAAI_ZeroRumor\zeroRumor_AAAI-main\src\dataset.py", line 602, in convert_fn
    inputs = tokenize_multipart_input(
  File "D:\AAAI_ZeroRumor\zeroRumor_AAAI-main\src\dataset.py", line 86, in tokenize_multipart_input
    relation = relation_dict['relation']
TypeError: 'int' object is not subscriptable
```
Could you please look into it?

**Comment by zjk000** [comment]
I also found that if I used the data provided in README, the relation information is included (so that the code can successfully run):
![relation](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/adae1296-55d0-42d1-b26c-c762f1b9cd9e)
However, if I used comment.py to process the raw data, the relation information is not included:
![norelation](https://github.com/PengyaoYi/zeroRumor_AAAI/assets/103090972/3c6c8bcb-3343-4f7b-9947-2485dc2c893f)

**Comment by zjk000** [comment]
solved
