### ISSUE TITLE
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--position_dataset', '--position', '--pooling_sent_limit', '128']

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#7]
作者您好，十分感谢您提供的代码更新。我在运行train.sh时遇到这个问题
```
(zeroRumor) zjk@zjk-MS-7C22:~/zjk/zeroRumor_AAAI-main$ ./train.sh 
/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/transformers/training_args.py:337: FutureWarning: The `evaluate_during_training` argument is deprecated in favor of `evaluation_strategy` (which has more options)
  warnings.warn(
Traceback (most recent call last):
  File "run.py", line 714, in <module>
    main()
  File "run.py", line 326, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/transformers/hf_argparser.py", line 152, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--position_dataset', '--position', '--pooling_sent_limit', '128']
```
我一开始认为是各种包的版本问题，于是我严格按照README中的版本来安装对应的依赖包，比如transformers为3.4.0，sentence-transformers为0.4.0，尽管如此，还是遇到了上述问题，特此向作者求助。

**Comment by Tiantian20000321** [comment]
+1

**Comment by DanielLin97** [comment]
Thank you for your issue. We will figure it out and give you feedback asap.

**Comment by DanielLin97** [comment]
We've fixed the issue you mentioned. Thank you for your patience.
