### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by zjk000** [PengyaoYi/zeroRumor_AAAI#8]
感谢作者对上一个issue的快速响应，换成最新版本的代码后运行train.sh仍然遇到以下问题：
```
Traceback (most recent call last):
  File "run.py", line 714, in <module>
    main()
  File "run.py", line 598, in main
    trainer.train(model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None)
  File "/home/zjk/zeroRumor_AAAI-main/src/trainer.py", line 394, in train
    tr_loss += self.training_step(model, inputs)
  File "/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/transformers/trainer.py", line 1056, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/transformers/trainer.py", line 1080, in compute_loss
    outputs = model(**inputs)
  File "/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjk/zeroRumor_AAAI-main/src/my_model.py", line 141, in forward
    key_structure = self.relation_encoder(relation_sent)
  File "/home/anaconda3/envs/zeroRumor/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zjk/zeroRumor_AAAI-main/src/my_model.py", line 31, in forward
    batch_size = relation_matrix.size(0)
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by Tiantian20000321** [comment]
你好，请问你是下载了他那个模型之后报的这个错吗

**Comment by zjk000** [comment]
> 你好，请问你是下载了他那个模型之后报的这个错吗

不是，因为README里的那个谷歌云盘需要访问权限，所以我就按论文里从HuggingFace上下了一个xlm-roberta-base。请问你能跑通吗？

**Comment by Tiantian20000321** [comment]
没有

**Comment by PengyaoYi** [comment]
fixed
